Cmn 1254 add udt
cybertec-postgresql/poc-plpgsql-analyzer pull request #130
Opened 2024-08-13 10:16 UTC by if-loop69420

## Summary
Add support for parsing user defined types through `CREATE TYPE`-statements

## What's been done?
- Add Tokens
- Add SyntaxKinds
- Add support element_spec
- Add parsing for everything
- Write massive amounts of tests
--- 
Have fun reviewing this massive change. This was so much work.
![](https://inspirationfeed.com/wp-content/uploads/2020/05/credit-card.jpg)

2024-08-21 09:17 UTC, KieranKaelin requested changes

2024-08-21 09:17 UTC, KieranKaelin commented on src/grammar/element_spec.rs
> +        _ => (),
Should there be an error here?

2024-08-21 10:24 UTC, if-loop69420 commented on src/grammar/udt.rs
> +#[allow(unused)]
Don't really have anywhere to put this right now sadly

2024-08-21 10:31 UTC, if-loop69420 commented on src/grammar/udt.rs
> +#[allow(unused)]
Other than this issue we can merge if we want

2024-08-21 10:34 UTC, KieranKaelin commented on src/grammar/udt.rs
> +    // Parse stupid bullshit
```suggestion
```

2024-08-21 10:37 UTC, KieranKaelin requested changes

2024-08-21 10:37 UTC, KieranKaelin commented on src/grammar/udt.rs
> +    ) ;",
Lets reduce this to the relevant parts:
```suggestion
                "CREATE TYPE customer_typ_demo AS OBJECT ( customer_id NUMBER(6)
    , cust_address       CUST_ADDRESS_TYP
    ) ;",
```

2024-08-21 10:37 UTC, KieranKaelin commented on src/grammar/udt.rs
> +       );",
Whats the difference to the test above?

2024-08-21 10:37 UTC, KieranKaelin commented on src/grammar/udt.rs
> +    );",
```suggestion
                "CREATE TYPE corporate_customer_typ_demo UNDER customer_typ (account_mgr_id     NUMBER(6));",
```

2024-08-21 10:54 UTC, if-loop69420 commented on src/grammar/udt.rs
> +       );",
true. This is redundant

2024-08-22 08:18 UTC, KieranKaelin approved these changes

2024-08-22 08:19 UTC, merged