Cmn 1248 add cte
cybertec-postgresql/poc-plpgsql-analyzer pull request #133
Opened 2024-08-21 13:08 UTC by if-loop69420

This is a reopening of #126 because i did it wrong.
---
![grafik](https://github.com/user-attachments/assets/f313d8c6-d460-4f30-b1c4-ba62022418ac)

2024-08-21 14:36 UTC, KieranKaelin requested changes

2024-08-21 14:36 UTC, KieranKaelin commented on src/grammar/function_invocation.rs
> +    if p.current().is_ident()
Good start, but we might have a function such as `my_schema.aggregate` :smile:

2024-08-21 14:36 UTC, KieranKaelin commented on src/grammar/query.rs
> +        dbg!(p.lookahead(3).as_slice());
```suggestion
```

2024-08-22 09:47 UTC, KieranKaelin commented on src/grammar/function_invocation.rs
> +    if p.current().is_ident()
The following `matches!` needs to be refactored to use `is_ident()` instead of `T![quoted_ident]` and `T![unquoted_ident]`.

2024-08-23 07:49 UTC, if-loop69420 commented on src/grammar/function_invocation.rs
> +
Idk. This is zach

2024-08-23 07:51 UTC, if-loop69420 commented on src/grammar/function_invocation.rs
> +
The matches was very nice visually, but that doesn't support functions.

2024-08-23 12:17 UTC, KieranKaelin approved these changes

2024-08-23 12:17 UTC, merged